"""Add time_logs table for employee time tracking

Revision ID: 12d20889191e
Revises: a42252748cb2
Create Date: 2025-12-02 11:40:20.646184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d20889191e'
down_revision: Union[str, None] = 'a42252748cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breaks', sa.Text(), nullable=True),
    sa.Column('total_break_duration', sa.Integer(), nullable=False),
    sa.Column('total_work_duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_BREAK', 'COMPLETED', name='timelogstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_time_log_created_at', 'time_logs', ['created_at'], unique=False)
    op.create_index('idx_time_log_date', 'time_logs', ['log_date'], unique=False)
    op.create_index('idx_time_log_status', 'time_logs', ['status'], unique=False)
    op.create_index('idx_time_log_user_created', 'time_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_time_log_user_date', 'time_logs', ['user_id', 'log_date'], unique=False)
    op.create_index('idx_time_log_user_id', 'time_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_time_logs_id'), 'time_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_logs_id'), table_name='time_logs')
    op.drop_index('idx_time_log_user_id', table_name='time_logs')
    op.drop_index('idx_time_log_user_date', table_name='time_logs')
    op.drop_index('idx_time_log_user_created', table_name='time_logs')
    op.drop_index('idx_time_log_status', table_name='time_logs')
    op.drop_index('idx_time_log_date', table_name='time_logs')
    op.drop_index('idx_time_log_created_at', table_name='time_logs')
    op.drop_table('time_logs')
    # ### end Alembic commands ###


