"""add time correction table

Revision ID: 1ac909bccdd0
Revises: 2e7d6f2a892e
Create Date: 2026-02-04 15:09:20.799213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ac909bccdd0'
down_revision: Union[str, None] = '2e7d6f2a892e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_correction_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('current_clock_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_clock_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_pause_periods', sa.Text(), nullable=True),
    sa.Column('requested_pause_periods', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='timecorrectionrequeststatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['time_trackers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tc_req_date', 'time_correction_requests', ['request_date'], unique=False)
    op.create_index('idx_tc_req_reviewer', 'time_correction_requests', ['reviewed_by'], unique=False)
    op.create_index('idx_tc_req_status_created', 'time_correction_requests', ['status', 'created_at'], unique=False)
    op.create_index('idx_tc_req_user_status', 'time_correction_requests', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_time_correction_requests_id'), 'time_correction_requests', ['id'], unique=False)
    op.create_table('time_correction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['time_correction_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tc_log_created', 'time_correction_logs', ['created_at'], unique=False)
    op.create_index('idx_tc_log_performer', 'time_correction_logs', ['performed_by'], unique=False)
    op.create_index('idx_tc_log_request', 'time_correction_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_time_correction_logs_id'), 'time_correction_logs', ['id'], unique=False)
    op.alter_column('email_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('email_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('email_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('employment_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('holidays', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('leaves', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('time_trackers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('time_trackers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('leaves', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('holidays', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('employment_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('email_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('email_settings', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('email_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_index(op.f('ix_time_correction_logs_id'), table_name='time_correction_logs')
    op.drop_index('idx_tc_log_request', table_name='time_correction_logs')
    op.drop_index('idx_tc_log_performer', table_name='time_correction_logs')
    op.drop_index('idx_tc_log_created', table_name='time_correction_logs')
    op.drop_table('time_correction_logs')
    op.drop_index(op.f('ix_time_correction_requests_id'), table_name='time_correction_requests')
    op.drop_index('idx_tc_req_user_status', table_name='time_correction_requests')
    op.drop_index('idx_tc_req_status_created', table_name='time_correction_requests')
    op.drop_index('idx_tc_req_reviewer', table_name='time_correction_requests')
    op.drop_index('idx_tc_req_date', table_name='time_correction_requests')
    op.drop_table('time_correction_requests')
    # ### end Alembic commands ###


