"""Initial migration

Revision ID: 30a4f8d3f0d9
Revises: d7a0d0eea66a
Create Date: 2025-10-27 11:11:26.877368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a4f8d3f0d9'
down_revision: Union[str, None] = 'd7a0d0eea66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


