"""add company_email and company_email_password to users

Revision ID: 489e6b3ebef7
Revises: be669eff6159
Create Date: 2025-11-03 11:24:26.916057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489e6b3ebef7'
down_revision: Union[str, None] = 'be669eff6159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_email_password', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_company_email'), 'users', ['company_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_email'), table_name='users')
    op.drop_column('users', 'company_email_password')
    op.drop_column('users', 'company_email')
    # ### end Alembic commands ###


