"""Initial migration

Revision ID: 9a08a65054b5
Revises: 7149e9a513eb
Create Date: 2025-10-27 12:11:30.343754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a08a65054b5'
down_revision: Union[str, None] = '7149e9a513eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_leave_balance', sa.Numeric(precision=5, scale=1), nullable=True))
        batch_op.add_column(sa.Column('total_leaves_taken', sa.Numeric(precision=5, scale=1), nullable=True))
        batch_op.add_column(sa.Column('total_leaves_remaining', sa.Numeric(precision=5, scale=1), nullable=True))
        batch_op.add_column(sa.Column('monthly_leave_allocation', sa.Numeric(precision=4, scale=1), nullable=True))
        batch_op.add_column(sa.Column('last_balance_update', sa.Date(), nullable=True))
        batch_op.create_index('idx_user_leave_balance', ['paid_leave_balance'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_leave_balance')
        batch_op.drop_column('last_balance_update')
        batch_op.drop_column('monthly_leave_allocation')
        batch_op.drop_column('total_leaves_remaining')
        batch_op.drop_column('total_leaves_taken')
        batch_op.drop_column('paid_leave_balance')

    # ### end Alembic commands ###


