"""create work_sessions and breaks tables

Revision ID: 9bcdc9e50ec4
Revises: c5e7e0ca3d74
Create Date: 2025-12-05 15:16:04.106468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcdc9e50ec4'
down_revision: Union[str, None] = 'c5e7e0ca3d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='trackerstatus'), nullable=False),
    sa.Column('pause_periods', sa.Text(), nullable=True),
    sa.Column('total_work_seconds', sa.Integer(), nullable=True),
    sa.Column('total_pause_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracker_created_at', 'time_trackers', ['created_at'], unique=False)
    op.create_index('idx_tracker_date', 'time_trackers', ['date'], unique=False)
    op.create_index('idx_tracker_status', 'time_trackers', ['status'], unique=False)
    op.create_index('idx_tracker_user_date', 'time_trackers', ['user_id', 'date'], unique=False)
    op.create_index('idx_tracker_user_id', 'time_trackers', ['user_id'], unique=False)
    op.create_index('idx_tracker_user_status', 'time_trackers', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_time_trackers_id'), 'time_trackers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_trackers_id'), table_name='time_trackers')
    op.drop_index('idx_tracker_user_status', table_name='time_trackers')
    op.drop_index('idx_tracker_user_id', table_name='time_trackers')
    op.drop_index('idx_tracker_user_date', table_name='time_trackers')
    op.drop_index('idx_tracker_status', table_name='time_trackers')
    op.drop_index('idx_tracker_date', table_name='time_trackers')
    op.drop_index('idx_tracker_created_at', table_name='time_trackers')
    op.drop_table('time_trackers')
    # ### end Alembic commands ###


