"""Add hardware_allocation and system_password to users

Revision ID: a1425e48cc83
Revises: 489e6b3ebef7
Create Date: 2025-11-03 12:35:35.319200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1425e48cc83'
down_revision: Union[str, None] = '489e6b3ebef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hardware_allocation', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('system_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'system_password')
    op.drop_column('users', 'hardware_allocation')
    # ### end Alembic commands ###


