"""merge EmployeeDetails into User

Revision ID: be669eff6159
Revises: 9a08a65054b5
Create Date: 2025-10-30 18:52:30.230887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be669eff6159'
down_revision: Union[str, None] = '9a08a65054b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_employee_active', table_name='employee_details')
    op.drop_index('idx_employee_clearance_status', table_name='employee_details')
    op.drop_index('idx_employee_created_at', table_name='employee_details')
    op.drop_index('idx_employee_department', table_name='employee_details')
    op.drop_index('idx_employee_employee_id', table_name='employee_details')
    op.drop_index('idx_employee_manager', table_name='employee_details')
    op.drop_index('idx_employee_probation_end_date', table_name='employee_details')
    op.drop_index('idx_employee_probation_status', table_name='employee_details')
    op.drop_index('idx_employee_termination_date', table_name='employee_details')
    op.drop_index('idx_employee_user_id', table_name='employee_details')
    op.drop_index('ix_employee_details_employee_id', table_name='employee_details')
    op.drop_index('ix_employee_details_id', table_name='employee_details')
    op.drop_table('employee_details')
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('users', sa.Column('personal_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_relation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('permanent_address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('work_location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('work_schedule', sa.String(), nullable=True))
    op.add_column('users', sa.Column('basic_salary', sa.String(), nullable=True))
    op.add_column('users', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ifsc_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('certifications', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('education_qualification', sa.String(), nullable=True))
    op.add_column('users', sa.Column('previous_experience_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('probation_period_months', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('probation_start_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('probation_end_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('probation_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('probation_review_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('probation_review_notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('probation_reviewer_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('termination_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('termination_reason', sa.String(), nullable=True))
    op.add_column('users', sa.Column('termination_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('termination_notice_period_days', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_working_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('termination_notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('termination_initiated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('exit_interview_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('exit_interview_notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('clearance_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('final_settlement_amount', sa.String(), nullable=True))
    op.add_column('users', sa.Column('final_settlement_date', sa.Date(), nullable=True))
    op.drop_index('idx_user_leave_balance', table_name='users')
    op.create_index('idx_user_clearance_status', 'users', ['clearance_status'], unique=False)
    op.create_index('idx_user_department', 'users', ['department'], unique=False)
    op.create_index('idx_user_manager', 'users', ['manager_id'], unique=False)
    op.create_index('idx_user_probation_end_date', 'users', ['probation_end_date'], unique=False)
    op.create_index('idx_user_probation_status', 'users', ['probation_status'], unique=False)
    op.create_index('idx_user_termination_date', 'users', ['termination_date'], unique=False)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['probation_reviewer_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['termination_initiated_by'], ['id'])
    op.drop_column('users', 'total_leaves_taken')
    op.drop_column('users', 'paid_leave_balance')
    op.drop_column('users', 'monthly_leave_allocation')
    op.drop_column('users', 'total_leaves_remaining')
    op.drop_column('users', 'last_balance_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_balance_update', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_leaves_remaining', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('monthly_leave_allocation', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('paid_leave_balance', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_leaves_taken', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index('idx_user_termination_date', table_name='users')
    op.drop_index('idx_user_probation_status', table_name='users')
    op.drop_index('idx_user_probation_end_date', table_name='users')
    op.drop_index('idx_user_manager', table_name='users')
    op.drop_index('idx_user_department', table_name='users')
    op.drop_index('idx_user_clearance_status', table_name='users')
    op.create_index('idx_user_leave_balance', 'users', ['paid_leave_balance'], unique=False)
    op.drop_column('users', 'final_settlement_date')
    op.drop_column('users', 'final_settlement_amount')
    op.drop_column('users', 'clearance_status')
    op.drop_column('users', 'exit_interview_notes')
    op.drop_column('users', 'exit_interview_date')
    op.drop_column('users', 'termination_initiated_by')
    op.drop_column('users', 'termination_notes')
    op.drop_column('users', 'last_working_date')
    op.drop_column('users', 'termination_notice_period_days')
    op.drop_column('users', 'termination_type')
    op.drop_column('users', 'termination_reason')
    op.drop_column('users', 'termination_date')
    op.drop_column('users', 'probation_reviewer_id')
    op.drop_column('users', 'probation_review_notes')
    op.drop_column('users', 'probation_review_date')
    op.drop_column('users', 'probation_status')
    op.drop_column('users', 'probation_end_date')
    op.drop_column('users', 'probation_start_date')
    op.drop_column('users', 'probation_period_months')
    op.drop_column('users', 'previous_experience_years')
    op.drop_column('users', 'education_qualification')
    op.drop_column('users', 'certifications')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'ifsc_code')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'bank_name')
    op.drop_column('users', 'currency')
    op.drop_column('users', 'basic_salary')
    op.drop_column('users', 'work_schedule')
    op.drop_column('users', 'work_location')
    op.drop_column('users', 'employment_type')
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'department')
    op.drop_column('users', 'country')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'permanent_address')
    op.drop_column('users', 'current_address')
    op.drop_column('users', 'emergency_contact_relation')
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'emergency_contact_name')
    op.drop_column('users', 'personal_email')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'marital_status')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'employee_id')
    op.create_table('employee_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('personal_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_relation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permanent_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_schedule', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('basic_salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('certifications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('education_qualification', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('previous_experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('probation_period_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('probation_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('probation_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('probation_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('probation_review_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('probation_review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('probation_reviewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('termination_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('termination_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('termination_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('termination_notice_period_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_working_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('termination_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('termination_initiated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exit_interview_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('exit_interview_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clearance_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_settlement_amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_settlement_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='employee_details_manager_id_fkey'),
    sa.ForeignKeyConstraint(['probation_reviewer_id'], ['users.id'], name='employee_details_probation_reviewer_id_fkey'),
    sa.ForeignKeyConstraint(['termination_initiated_by'], ['users.id'], name='employee_details_termination_initiated_by_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='employee_details_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employee_details_pkey'),
    sa.UniqueConstraint('user_id', name='employee_details_user_id_key')
    )
    op.create_index('ix_employee_details_id', 'employee_details', ['id'], unique=False)
    op.create_index('ix_employee_details_employee_id', 'employee_details', ['employee_id'], unique=True)
    op.create_index('idx_employee_user_id', 'employee_details', ['user_id'], unique=False)
    op.create_index('idx_employee_termination_date', 'employee_details', ['termination_date'], unique=False)
    op.create_index('idx_employee_probation_status', 'employee_details', ['probation_status'], unique=False)
    op.create_index('idx_employee_probation_end_date', 'employee_details', ['probation_end_date'], unique=False)
    op.create_index('idx_employee_manager', 'employee_details', ['manager_id'], unique=False)
    op.create_index('idx_employee_employee_id', 'employee_details', ['employee_id'], unique=False)
    op.create_index('idx_employee_department', 'employee_details', ['department'], unique=False)
    op.create_index('idx_employee_created_at', 'employee_details', ['created_at'], unique=False)
    op.create_index('idx_employee_clearance_status', 'employee_details', ['clearance_status'], unique=False)
    op.create_index('idx_employee_active', 'employee_details', ['is_active'], unique=False)
    # ### end Alembic commands ###


