"""initial schema

Revision ID: c5e7e0ca3d74
Revises: 
Create Date: 2025-12-05 12:49:20.330618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e7e0ca3d74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_log_created', 'email_logs', ['created_at'], unique=False)
    op.create_index('idx_email_log_recipient', 'email_logs', ['recipient_email'], unique=False)
    op.create_index('idx_email_log_status', 'email_logs', ['status'], unique=False)
    op.create_index('idx_email_log_template', 'email_logs', ['template_type'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_server', sa.String(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(), nullable=False),
    sa.Column('smtp_password', sa.String(), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('smtp_use_ssl', sa.Boolean(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('from_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_settings_active', 'email_settings', ['is_active'], unique=False)
    op.create_index(op.f('ix_email_settings_id'), 'email_settings', ['id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_email_template_active', 'email_templates', ['is_active'], unique=False)
    op.create_index('idx_email_template_type', 'email_templates', ['template_type'], unique=False)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holiday_active', 'holidays', ['is_active'], unique=False)
    op.create_index('idx_holiday_date', 'holidays', ['date'], unique=False)
    op.create_index('idx_holiday_date_active', 'holidays', ['date', 'is_active'], unique=False)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('wifi_user_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('aadhaar_front', sa.String(), nullable=True),
    sa.Column('aadhaar_back', sa.String(), nullable=True),
    sa.Column('pan_image', sa.String(), nullable=True),
    sa.Column('profile_image_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=True),
    sa.Column('aadhaar_front_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=True),
    sa.Column('aadhaar_back_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=True),
    sa.Column('pan_image_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('personal_email', sa.String(), nullable=True),
    sa.Column('company_email', sa.String(), nullable=True),
    sa.Column('company_email_password', sa.String(), nullable=True),
    sa.Column('hardware_allocation', sa.Text(), nullable=True),
    sa.Column('system_password', sa.String(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('work_location', sa.String(), nullable=True),
    sa.Column('work_schedule', sa.String(), nullable=True),
    sa.Column('basic_salary', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('ifsc_code', sa.String(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('education_qualification', sa.String(), nullable=True),
    sa.Column('previous_experience_years', sa.Integer(), nullable=True),
    sa.Column('probation_period_months', sa.Integer(), nullable=True),
    sa.Column('probation_start_date', sa.Date(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('probation_status', sa.String(), nullable=True),
    sa.Column('probation_review_date', sa.Date(), nullable=True),
    sa.Column('probation_review_notes', sa.Text(), nullable=True),
    sa.Column('probation_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('termination_reason', sa.String(), nullable=True),
    sa.Column('termination_type', sa.String(), nullable=True),
    sa.Column('termination_notice_period_days', sa.Integer(), nullable=True),
    sa.Column('last_working_date', sa.Date(), nullable=True),
    sa.Column('termination_notes', sa.Text(), nullable=True),
    sa.Column('termination_initiated_by', sa.Integer(), nullable=True),
    sa.Column('exit_interview_date', sa.Date(), nullable=True),
    sa.Column('exit_interview_notes', sa.Text(), nullable=True),
    sa.Column('clearance_status', sa.String(), nullable=True),
    sa.Column('final_settlement_amount', sa.String(), nullable=True),
    sa.Column('final_settlement_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['probation_reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['termination_initiated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_clearance_status', 'users', ['clearance_status'], unique=False)
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_department', 'users', ['department'], unique=False)
    op.create_index('idx_user_manager', 'users', ['manager_id'], unique=False)
    op.create_index('idx_user_probation_end_date', 'users', ['probation_end_date'], unique=False)
    op.create_index('idx_user_probation_status', 'users', ['probation_status'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index('idx_user_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index('idx_user_termination_date', 'users', ['termination_date'], unique=False)
    op.create_index(op.f('ix_users_company_email'), 'users', ['company_email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_wifi_user_id'), 'users', ['wifi_user_id'], unique=False)
    op.create_table('employment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('work_location', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('reporting_manager_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason_for_change', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employment_created_at', 'employment_history', ['created_at'], unique=False)
    op.create_index('idx_employment_current', 'employment_history', ['is_current'], unique=False)
    op.create_index('idx_employment_dates', 'employment_history', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_employment_department', 'employment_history', ['department'], unique=False)
    op.create_index('idx_employment_manager', 'employment_history', ['manager_id'], unique=False)
    op.create_index('idx_employment_position', 'employment_history', ['position_title'], unique=False)
    op.create_index('idx_employment_user_id', 'employment_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_employment_history_id'), 'employment_history', ['id'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leave_created_at', 'leaves', ['created_at'], unique=False)
    op.create_index('idx_leave_dates', 'leaves', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_leave_status', 'leaves', ['status'], unique=False)
    op.create_index('idx_leave_user_created', 'leaves', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_leave_user_id', 'leaves', ['user_id'], unique=False)
    op.create_index('idx_leave_user_status', 'leaves', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.Enum('ERROR', 'SUCCESS', name='logtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('request_path', sa.String(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_created_at', 'logs', ['created_at'], unique=False)
    op.create_index('idx_log_module', 'logs', ['module'], unique=False)
    op.create_index('idx_log_type', 'logs', ['log_type'], unique=False)
    op.create_index('idx_log_type_created', 'logs', ['log_type', 'created_at'], unique=False)
    op.create_index('idx_log_user_id', 'logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_active', 'tasks', ['is_active'], unique=False)
    op.create_index('idx_task_category', 'tasks', ['category'], unique=False)
    op.create_index('idx_task_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_task_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_task_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_task_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_task_user_created', 'tasks', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_task_user_id', 'tasks', ['user_id'], unique=False)
    op.create_index('idx_task_user_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index('idx_task_user_status', table_name='tasks')
    op.drop_index('idx_task_user_id', table_name='tasks')
    op.drop_index('idx_task_user_created', table_name='tasks')
    op.drop_index('idx_task_status', table_name='tasks')
    op.drop_index('idx_task_priority', table_name='tasks')
    op.drop_index('idx_task_due_date', table_name='tasks')
    op.drop_index('idx_task_created_at', table_name='tasks')
    op.drop_index('idx_task_category', table_name='tasks')
    op.drop_index('idx_task_active', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index('idx_log_user_id', table_name='logs')
    op.drop_index('idx_log_type_created', table_name='logs')
    op.drop_index('idx_log_type', table_name='logs')
    op.drop_index('idx_log_module', table_name='logs')
    op.drop_index('idx_log_created_at', table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_index('idx_leave_user_status', table_name='leaves')
    op.drop_index('idx_leave_user_id', table_name='leaves')
    op.drop_index('idx_leave_user_created', table_name='leaves')
    op.drop_index('idx_leave_status', table_name='leaves')
    op.drop_index('idx_leave_dates', table_name='leaves')
    op.drop_index('idx_leave_created_at', table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_employment_history_id'), table_name='employment_history')
    op.drop_index('idx_employment_user_id', table_name='employment_history')
    op.drop_index('idx_employment_position', table_name='employment_history')
    op.drop_index('idx_employment_manager', table_name='employment_history')
    op.drop_index('idx_employment_department', table_name='employment_history')
    op.drop_index('idx_employment_dates', table_name='employment_history')
    op.drop_index('idx_employment_current', table_name='employment_history')
    op.drop_index('idx_employment_created_at', table_name='employment_history')
    op.drop_table('employment_history')
    op.drop_index(op.f('ix_users_wifi_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_email'), table_name='users')
    op.drop_index('idx_user_termination_date', table_name='users')
    op.drop_index('idx_user_role_active', table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_probation_status', table_name='users')
    op.drop_index('idx_user_probation_end_date', table_name='users')
    op.drop_index('idx_user_manager', table_name='users')
    op.drop_index('idx_user_department', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_index('idx_user_clearance_status', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index('idx_holiday_date_active', table_name='holidays')
    op.drop_index('idx_holiday_date', table_name='holidays')
    op.drop_index('idx_holiday_active', table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_index('idx_email_template_type', table_name='email_templates')
    op.drop_index('idx_email_template_active', table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_email_settings_id'), table_name='email_settings')
    op.drop_index('idx_email_settings_active', table_name='email_settings')
    op.drop_table('email_settings')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index('idx_email_log_template', table_name='email_logs')
    op.drop_index('idx_email_log_status', table_name='email_logs')
    op.drop_index('idx_email_log_recipient', table_name='email_logs')
    op.drop_index('idx_email_log_created', table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###


